### Perceptron Algorithm 
Implementation of the Algorithm for managing the weights and the bias of a single perceptron

![title](perceptron.jpg)

In [5]:
import numpy as np
# Setting the random seed, feel free to change it and see different solutions.
np.random.seed(42)

### Step Function
Function that generates the output of the perceptron based on the values of its input weighted by the input weight and the bias

![title](step.jpg)

In [6]:
def stepFunction(t):
    if t >= 0:
        return 1
    return 0

### Nucleus of the Perceptron
Components of the Peceptron that makes the actual prediction based on the inputs, weights and bias

![title](nucleus.jpg)

In [7]:
def prediction(X, W, b):
    return stepFunction((np.matmul(X,W)+b)[0])

In [34]:
# Implement the perceptron trick.
# The function should receive as inputs the data X, the labels y,
# the weights W (as an array), and the bias b,
# update the weights and bias W, b, according to the perceptron algorithm,
# and return W and b.
def perceptronStep(X, y, W, b, learn_rate = 0.01):
    
    for i, x in enumerate(X):
        y_pred = prediction(x, W, b)
        if y_pred != y[i]:
            if y_pred == 0:
                # Increment the Weights
                W[0] += learn_rate * x[0]
                W[1] += learn_rate * x[1]
                b += learn_rate
            else:
                # decrement the Weights
                W[0] -= learn_rate * x[0]
                W[1] -= learn_rate * x[1]
                b -= learn_rate
    
    
    return W, b

### Update the Weights 
Find the optimal line that categorize correctly most of the points

In [35]:
# This function runs the perceptron algorithm repeatedly on the dataset,
# and returns a few of the boundary lines obtained in the iterations,
# for plotting purposes.
# Feel free to play with the learning rate and the num_epochs,
# and see your results plotted below.
def trainPerceptronAlgorithm(X, y, learn_rate = 0.01, num_epochs = 25):
    x_min, x_max = min(X.T[0]), max(X.T[0])
    y_min, y_max = min(X.T[1]), max(X.T[1])
    W = np.array(np.random.rand(2,1))
    b = np.random.rand(1)[0] + x_max
    # These are the solution lines that get plotted below.
    boundary_lines = []
    for i in range(num_epochs):
        # In each epoch, we apply the perceptron step.
        W, b = perceptronStep(X, y, W, b, learn_rate)
        boundary_lines.append((-W[0]/W[1], -b/W[1]))
    return boundary_lines

### Load the Data and Run

In [36]:
import pandas as pd

df = pd.read_csv('data.csv', header=None)
X = df.iloc[:, 0:2].to_numpy()
y = df.iloc[:, 2].to_numpy()

trainPerceptronAlgorithm(X, y)

[(array([1.32111616]), array([3.39038455])),
 (array([-0.02727335]), array([0.58093127])),
 (array([-0.06953723]), array([0.5033617])),
 (array([-0.09336359]), array([0.50938365])),
 (array([-0.11776695]), array([0.51555142])),
 (array([-0.14276851]), array([0.52187039])),
 (array([-0.16839056]), array([0.52834619])),
 (array([-0.19465648]), array([0.53498471])),
 (array([-0.20547521]), array([0.57024877])),
 (array([-0.22495207]), array([0.57724872])),
 (array([-0.24289533]), array([0.58594893])),
 (array([-0.26138775]), array([0.5949154])),
 (array([-0.28045492]), array([0.60416056])),
 (array([-0.30012406]), array([0.6136976])),
 (array([-0.32842636]), array([0.5900821])),
 (array([-0.34182866]), array([0.63222086])),
 (array([-0.37108442]), array([0.6079341])),
 (array([-0.38612915]), array([0.65189711])),
 (array([-0.4164041]), array([0.62689996])),
 (array([-0.44025201]), array([0.63605195])),
 (array([-0.44738156]), array([0.67836799])),
 (array([-0.46823366]), array([0.64805537