### Save and Load Weights and Bias

### Saving Variables
Save random Weights and Biases to the local storage

In [3]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

# The file path to save the data
save_file = './model.ckpt'

# Two Tensor Variables: weights and bias
weights = tf.Variable(tf.truncated_normal([2, 3]))
bias = tf.Variable(tf.truncated_normal([3]))

# Class used to save and/or restore Tensor Variables
saver = tf.train.Saver()

with tf.Session() as sess:
    # Initialize all the Variables
    sess.run(tf.global_variables_initializer())

    # Show the values of weights and bias
    print('Weights:')
    print(sess.run(weights))
    print('Bias:')
    print(sess.run(bias))

    # Save the model
    saver.save(sess, save_file)

Weights:
[[-0.3180638  -0.8761303   1.0722998 ]
 [-0.66965973  1.550199   -0.93705153]]
Bias:
[ 0.34937125  1.1475382  -0.98367673]


### Loading Variables
Restore Weights and Baises from the local storage

In [4]:
# Remove the previous weights and bias
tf.reset_default_graph()

# Two Variables: weights and bias
weights = tf.Variable(tf.truncated_normal([2, 3]))
bias = tf.Variable(tf.truncated_normal([3]))

# Class used to save and/or restore Tensor Variables
saver = tf.train.Saver()

with tf.Session() as sess:
    # Load the weights and bias
    saver.restore(sess, save_file)

    # Show the values of weights and bias
    print('Weight:')
    print(sess.run(weights))
    print('Bias:')
    print(sess.run(bias))

INFO:tensorflow:Restoring parameters from ./model.ckpt
Weight:
[[ 1.4254434   0.36075634  0.43270606]
 [-0.40388948  1.6136608  -1.0529608 ]]
Bias:
[-0.5979086   0.57426995 -1.8632501 ]
